/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Colors API
 * 色API
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, delay, http } from "msw";

import type { ColorListResponse } from "../schemas";

export const getGetApiColorsResponseMock = (): ColorListResponse => [
  "red",
  "green",
  "blue",
];

export const getGetApiColorsMockHandler = (
  overrideResponse?:
    | ColorListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<ColorListResponse> | ColorListResponse)
) => {
  return http.get("*/api/colors", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApiColorsResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};
export const getColorsAPIMock = () => [getGetApiColorsMockHandler()];
