/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Colors API
 * 色API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 標準的なエラーレスポンス
 */
export interface ErrorResponse {
	/** エラーの詳細メッセージ */
	message: string;
}
